# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/project
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Configure deploy permissions
          command: pwd && sudo chmod -R 400 ./deploy/*
      - run:
          name: Configure www ownership
          command: ssh -i ./deploy/ocean-landing-aws.pem root@entelocean.cl "sudo chown -R ubuntu:ubuntu /var/www/"
      - run:
          name: Configure www permissions
          command: ssh -i ./deploy/ocean-landing-aws.pem root@entelocean.cl "sudo chmod -R 777 /var/www/"
      - run:
          name: upgrade rsync
          command: sudo apt-get install --only-upgrade rsync
      - run:
          name: Deploy to the server
          command: rsync -rzO -e 'ssh -i ./deploy/ocean-landing-aws.pem -p 22' ./ root@entelocean.cl:/var/www
workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: master