# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/ocean-landing
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
      steps:
        - sudo chmod -R 400 ~/ocean-landing/deploy/*
        - ssh -i ~/ocean-landing/deploy/ocean-landing.pem ubuntu@entelocean.com "sudo chmod -R 777 /var/www/"
        - ssh -i ~/ocean-landing/deploy/ocean-landing.pem ubuntu@entelocean.com "sudo chown -R ubuntu:ubuntu /var/www/"
        - rsync -rzO -e 'ssh -i ~/ocean-landing/deploy/ocean-landing.pem -p 22' ~/ocean-landing centos@entelocean.com:/var/www